library(tidyverse)
library(magrittr)
library(stringr)
library(quanteda)
library(readtext)
library(ggplot2)
library(e1071)
library(irlba)
library(randomForest)
library(tm)
library(dplyr)
library(class)
library(NLP)
library(stringr)
library(wordcloud)
#library(tau)
dat <- paste(readLines('einstein.txt'), collapse=" ")
str(dat)

corpus <- corpus(dat)
corpus <- tm_map(corpus, content_transformer(tolower))
corpus <- tm_map(corpus, removePunctuation)
corpus <- tm_map(corpus, stripWhitespace)
corpus <- tm_map(corpus, removeWords, stopwords("english"))
#corpus <- removeWords(corpus, stopwords("english"))
dat2 <- Corpus(VectorSource(as.vector(corpus)))
dat3 <- DocumentTermMatrix(dat2)
dat4 <- as.matrix(dat3)
dat4
frequency <- colSums(dat4)
frequency <- sort(frequency, decreasing = TRUE)
words <- names(frequency)
wordcloud(words[1:100], frequency[1:100])



